server:
  port: 8085


spring:
  application:
    name: code-generate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://github.com/baomidou/dynamic-datasource-spring-boot-starter
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: false
      # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata: false
      # 严格模式 匹配不到数据源则报错
      strict: true
      primary: sup
      datasource:
        sup:
          url: jdbc:mysql://192.168.1.25:3306/supplier?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: zhgd_v2_dev
          password: zhgd_v2_dev
          driver-class-name: com.mysql.cj.jdbc.Driver
        cost:
          url: jdbc:mysql://192.168.1.25:3306/hujiang-cloud-dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: zhgd_v2_dev
          password: zhgd_v2_dev
          driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 10000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 60000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 900000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.aprilz.generate.entity
  global-config:
    # \u6570\u636E\u5E93\u76F8\u5173\u914D\u7F6E
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: AUTO
      #\u5B57\u6BB5\u7B56\u7565 IGNORED:"\u5FFD\u7565\u5224\u65AD",NOT_NULL:"\u975E NULL \u5224\u65AD"),NOT_EMPTY:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: NOT_EMPTY
      #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
      column-underline: true
      #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
      #capital-mode: true
      #\u903B\u8F91\u5220\u9664\u914D\u7F6E
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    refresh: true
  # \u539F\u751F\u914D\u7F6E
  configuration:
    map-underscore-to-camel-case: true
    #\u5F00\u542F Mybatis \u4E8C\u7EA7\u7F13\u5B58\uFF0C\u9ED8\u8BA4\u4E3A true\u3002
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


codegen:
  base-package: com.hujiang
  db-schemas: hujiang
