version: '3'
services:
  security_gene:
    image: code_gengrate:latest
    container_name: security_gene
    restart: always
    ports:
      - 8086:8086
    networks:
      - ap
    privileged: true
networks:
  ap:
    external: true
